---
all:
  children:
    local:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python
    remote:
      hosts:
        # kali-target:
        #   ansible_host: 192.168.0.43
        #   ansible_user: kali
        #   ansible_python_interpreter: /usr/bin/python
