---
- name: Set default locale to {{ system_locale }}
  become: true
  ansible.builtin.debconf:
    name: locales
    question: locales/default_environment_locale
    value: "{{ system_locale }}"
    vtype: select

- name: Enable and generate the locale {{ system_locale }}
  become: true
  community.general.locale_gen:
    name: "{{ system_locale }}"
    state: present

- name: Set system locale
  become: true
  ansible.builtin.copy:
    dest: /etc/default/locale
    content: |
      LANG={{ system_locale }}
      LANGUAGE={{ system_language }}
      LC_ALL={{ system_locale }}
    mode: '0644'

- name: Set keyboard layout to {{ system_keyboard_layout }}
  become: true
  ansible.builtin.debconf:
    name: keyboard-configuration
    question: keyboard-configuration/layoutcode
    value: "{{ system_keyboard_layout }}"
    vtype: string

- name: Set keyboard model to {{ system_keyboard_model }}
  become: true
  ansible.builtin.debconf:
    name: keyboard-configuration
    question: keyboard-configuration/modelcode
    value: "{{ system_keyboard_model }}"
    vtype: string

- name: Configure keyboard defaults
  become: true
  ansible.builtin.copy:
    dest: /etc/default/keyboard
    content: |
      XKBMODEL="{{ system_keyboard_model }}"
      XKBLAYOUT="{{ system_keyboard_layout }}"
      XKBVARIANT=""
      XKBOPTIONS=""
      BACKSPACE="guess"
    mode: '0644'
  register: system_keyboard_config

- name: Apply keyboard configuration
  become: true
  ansible.builtin.command:
    cmd: dpkg-reconfigure -f noninteractive keyboard-configuration
  when: system_keyboard_config.changed
  changed_when: true

- name: Set timezone to {{ system_timezone }}
  become: true
  community.general.timezone:
    name: "{{ system_timezone }}"
