---
- name: Install tools from upstream installer scripts
  ansible.builtin.include_tasks: _install_script.yaml
  loop: "{{ tools_install_scripts }}"
  loop_control:
    loop_var: tools_install_script
    label: "{{ tools_install_script.name }}"

- name: Copy the gdbinit file
  ansible.builtin.copy:
    src: gdbinit
    dest: "{{ ansible_facts['env']['HOME'] }}/.gdbinit"
    mode: '0664'
