---
- name: Configure Git defaults
  block:
    - name: Set default branch to main
      community.general.git_config:
        name: init.defaultBranch
        scope: global
        value: main

    - name: Auto setup remote tracking branch on push
      community.general.git_config:
        name: push.autoSetupRemote
        scope: global
        value: "true"

    - name: Set default push behaviour to current branch
      community.general.git_config:
        name: push.default
        scope: global
        value: current

    - name: Enable pull with rebase by default
      community.general.git_config:
        name: pull.rebase
        scope: global
        value: "true"

    - name: Set default editor to vim
      community.general.git_config:
        name: core.editor
        scope: global
        value: nano

- name: Get latest checksec version from GitHub
  ansible.builtin.uri:
    url: https://api.github.com/repos/slimm609/checksec/releases/latest
    return_content: true
  register: tools_git_checksec_versions
  changed_when: false

- name: Extract the version into a variable
  ansible.builtin.set_fact:
    tools_checksec_version: "{{ tools_git_checksec_versions.json.tag_name }}"

- name: Install checksec .deb package
  become: true
  ansible.builtin.apt:
    deb: "https://github.com/slimm609/checksec/releases/download/{{ tools_checksec_version }}/checksec_{{ tools_checksec_version }}_amd64.deb"
