---
- name: Install global Python packages
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
    break_system_packages: true
  loop: "{{ tools_pip_packages }}"

- name: Install tools via pipx
  community.general.pipx:
    state: present
    name: "{{ item }}"
    install_deps: true
  environment:
    PATH: "{{ ansible_facts['env']['HOME'] }}/.cargo/bin:{{ ansible_facts['env']['PATH'] }}"
  loop: "{{ tools_pipx_packages }}"

- name: Inject packages into existing virtual environments
  community.general.pipx:
    state: inject
    name: "{{ item.name }}"
    inject_packages: "{{ item.inject }}"
  loop: "{{ tools_pipx_injections }}"

- name: Install uv
  ansible.builtin.include_tasks: _install_script.yaml
  vars:
    tools_install_script:
      name: uv
      url: https://astral.sh/uv/install.sh
      creates: "{{ ansible_facts['env']['HOME'] }}/.local/bin/uv"
