---
- name: Install global Python packages
  ansible.builtin.pip:
    name: pwntools
    state: present
    break_system_packages: true
  loop:
    - pwntools
    - angr

- name: Install tools via pipx
  community.general.pipx:
    state: present
    name: "{{ item }}"
    install_deps: true
  loop:
    - bandit
    - clairvoyance
    - defaultcreds-cheat-sheet
    - git+https://github.com/brightio/penelope
    - git+https://github.com/Pennyw0rth/NetExec
    - smbclientng
    - ssh-audit
    - updog
    - wesng

- name: Inject packages into existing virtual environments
  community.general.pipx:
    state: inject
    name: "{{ item.name }}"
    inject_packages: "{{ item.inject }}"
  loop:
    - { name: 'wesng', inject: 'chardet' }

- name: Install uv
  block:
    - name: Check if uv is already installed
      ansible.builtin.stat:
        path: "{{ ansible_facts['env']['HOME'] }}/.local/bin/uv"
      register: tools_uv_installed

    - name: Download uv installer
      ansible.builtin.get_url:
        url: https://astral.sh/uv/install.sh
        dest: /tmp/uv-init.sh
        mode: '0755'
      when: not tools_uv_installed.stat.exists

    - name: Run uv installer
      ansible.builtin.command: /tmp/uv-init.sh
      when: not tools_uv_installed.stat.exists
      changed_when: true

    - name: Clean up uv installer
      ansible.builtin.file:
        path: /tmp/uv-init.sh
        state: absent
