---
- name: Install the Rust toolchain
  block:
    - name: Install rustup
      ansible.builtin.include_tasks: _install_script.yaml
      vars:
        tools_install_script:
          name: rustup
          url: https://sh.rustup.rs
          creates: "{{ ansible_facts['env']['HOME'] }}/.cargo/bin/rustup"
          args:
            - -y

    - name: Configure ~/.zshrc to source Cargo environment
      ansible.builtin.blockinfile:
        path: "{{ ansible_facts['env']['HOME'] }}/.zshrc"
        marker: "# {mark} ANSIBLE MANAGED BLOCK - Cargo env"
        append_newline: true
        prepend_newline: true
        block: |
          . "$HOME/.cargo/env"

    - name: Install some crates via Cargo (will take some time)
      community.general.cargo:
        name: "{{ tools_cargo_crates }}"
        locked: true
        state: present
        executable: "{{ ansible_facts['env']['HOME'] }}/.cargo/bin/cargo"

    - name: Configure ~/.zshrc to use starship & zellij
      ansible.builtin.blockinfile:
        path: "{{ ansible_facts['env']['HOME'] }}/.zshrc"
        marker: "# {mark} ANSIBLE MANAGED BLOCK - starship & zellij"
        append_newline: true
        prepend_newline: true
        block: |
          if [[ "$TERM_PROGRAM" != "vscode" ]]; then
            eval "$(zellij setup --generate-auto-start zsh)"
          fi
          eval "$(starship init zsh)"

    - name: Ensure the zellij config directory exists
      ansible.builtin.file:
        path: "{{ ansible_facts['env']['HOME'] }}/.config/zellij"
        state: directory
        mode: '0775'

    - name: Install xsel to get a working clipboard inside zellij
      become: true
      ansible.builtin.apt:
        state: present
        update_cache: true
        pkg:
          - xsel

    - name: Copy the customised Zellij config
      ansible.builtin.copy:
        src: zellij_config.kdl
        dest: "{{ ansible_facts['env']['HOME'] }}/.config/zellij/config.kdl"
        mode: '0664'
